### ISSUE TITLE
Realtek rtl8723de not working

### ISSUE THREAD

**Issue by aldajulian** [arnoldthebat/chromiumos#236]
I use HP laptop, and chromium os version arnoldthebat working great, except 1 thing, the wireless and bluetooth not working, for this Realtek rtl8723de driver, LAN working well.

Thankyou.

**Comment by aldajulian** [comment]
Btw, there is public repo that have this driver for linux, Can I install it manually by my self? or can you give me an instruction?

repo: https://github.com/smlinux/rtl8723de

Thanks.

**Comment by arnoldthebat** [comment]
Please test in the latest alpha build and feedback. Hopefully this is fixed now

**Comment by aldajulian** [comment]
Thanks, will do

**Comment by aldajulian** [comment]
the bluetooth works well, but the wifi still not working, it disabled
